import type { OntologySnapshot } from "./types.js";

const analytical = {
  description: "",
  sensitive: false,
  visibility: "ANALYTICAL" as const,
  synonyms: [] as string[],
  defaultDisplay: false,
  exportable: true,
  bindingPriority: 50,
};

export const sampleSnapshot: OntologySnapshot = {
  schemaVersion: 2,
  version: 12,
  baseVersion: 12,
  status: "DRAFT",
  objects: [
    {
      id: "obj_sales",
      name: "sales_event",
      label: "销售事件",
      description: "一行代表一笔已入账的订单明细",
      sourceTableId: "fact_sales",
      status: "DRAFT",
      objectType: "EVENT",
      grainPropertyIds: ["prop_sales_id"],
      grain: "订单明细",
      defaultTimePropertyId: "prop_order_time",
      defaultFilter: "is_deleted = 0",
      synonyms: ["销售", "订单", "成交"],
      bindingPriority: 100,
      properties: [
        { ...analytical, id: "prop_sales_id", name: "sales_id", label: "销售明细 ID", dataType: "BIGINT", sourceColumn: "sales_id", meaning: "ID", unique: true, valueSearchable: false },
        { ...analytical, id: "prop_customer_id", name: "customer_id", label: "客户引用", dataType: "BIGINT", sourceColumn: "customer_id", meaning: "ENTITY_REFERENCE", unique: false, valueSearchable: false },
        { ...analytical, id: "prop_region_id", name: "region_id", label: "区域引用", dataType: "BIGINT", sourceColumn: "region_id", meaning: "ENTITY_REFERENCE", unique: false, valueSearchable: false },
        { ...analytical, id: "prop_channel", name: "channel", label: "销售渠道", dataType: "VARCHAR", sourceColumn: "channel_name", meaning: "CATEGORY", unique: false, valueSearchable: true, synonyms: ["渠道", "来源"] },
        { ...analytical, id: "prop_order_time", name: "order_time", label: "下单时间", dataType: "DATETIME", sourceColumn: "order_time", meaning: "TIME", unique: false, valueSearchable: false, synonyms: ["订单日期", "销售时间"] },
        { ...analytical, id: "prop_sales_amount", name: "sales_amount", label: "销售金额", dataType: "DECIMAL", sourceColumn: "sales_amount", meaning: "NUMBER", unique: false, valueSearchable: false, numericSpec: { kind: "CURRENCY", currency: "CNY", defaultAggregation: "SUM", aggregationBehavior: "ADDITIVE" } },
        { ...analytical, id: "prop_cost_amount", name: "cost_amount", label: "成本金额", dataType: "DECIMAL", sourceColumn: "cost_amount", meaning: "NUMBER", unique: false, valueSearchable: false, numericSpec: { kind: "CURRENCY", currency: "CNY", defaultAggregation: "SUM", aggregationBehavior: "ADDITIVE" } },
      ],
    },
    {
      id: "obj_customer",
      name: "customer",
      label: "客户",
      description: "一行代表一个有效客户",
      sourceTableId: "dim_customer",
      status: "DRAFT",
      objectType: "ENTITY",
      grainPropertyIds: ["prop_customer_pk"],
      grain: "客户",
      defaultFilter: "is_active = 1",
      synonyms: ["顾客", "会员"],
      bindingPriority: 80,
      properties: [
        { ...analytical, id: "prop_customer_pk", name: "customer_id", label: "客户 ID", dataType: "BIGINT", sourceColumn: "customer_id", meaning: "ID", unique: true, valueSearchable: false },
        { ...analytical, id: "prop_customer_name", name: "customer_name", label: "客户名称", dataType: "VARCHAR", sourceColumn: "customer_name", meaning: "NAME", unique: false, valueSearchable: true, defaultDisplay: true, synonyms: ["客户名"] },
      ],
    },
    {
      id: "obj_region",
      name: "region",
      label: "区域",
      description: "一行代表一个标准销售区域",
      sourceTableId: "dim_region",
      status: "DRAFT",
      objectType: "ENTITY",
      grainPropertyIds: ["prop_region_pk"],
      grain: "销售区域",
      synonyms: ["地区", "大区"],
      bindingPriority: 90,
      properties: [
        { ...analytical, id: "prop_region_pk", name: "region_id", label: "区域 ID", dataType: "BIGINT", sourceColumn: "region_id", meaning: "ID", unique: true, valueSearchable: false },
        { ...analytical, id: "prop_region_name", name: "region_name", label: "区域名称", dataType: "VARCHAR", sourceColumn: "region_name", meaning: "GEOGRAPHY", unique: true, valueSearchable: true, defaultDisplay: true, synonyms: ["大区名称", "地区"] },
      ],
    },
  ],
  metrics: [
    { id: "metric_sales", metricType: "BASE", name: "sales_amount", label: "销售额", description: "已入账销售金额合计", objectId: "obj_sales", definitionMode: "VISUAL", expression: "", sourcePropertyId: "prop_sales_amount", aggregation: "SUM", format: "currency", unit: "元", synonyms: ["销售金额", "成交额", "GMV"], status: "DRAFT" },
    { id: "metric_cost", metricType: "BASE", name: "cost_amount", label: "成本额", description: "销售对应成本金额合计", objectId: "obj_sales", definitionMode: "VISUAL", expression: "", sourcePropertyId: "prop_cost_amount", aggregation: "SUM", format: "currency", unit: "元", synonyms: ["成本"], status: "DRAFT" },
    { id: "metric_profit", metricType: "DERIVED", name: "gross_profit", label: "毛利额", description: "销售额减去成本额", objectId: "obj_sales", definitionMode: "VISUAL", expression: "", aggregation: "CUSTOM", leftMetricId: "metric_sales", rightMetricId: "metric_cost", calculationOperator: "SUBTRACT", format: "currency", unit: "元", synonyms: ["毛利"], status: "DRAFT" },
    { id: "metric_margin", metricType: "DERIVED", name: "gross_margin", label: "毛利率", description: "毛利额占销售额的比例", objectId: "obj_sales", definitionMode: "VISUAL", expression: "", aggregation: "CUSTOM", leftMetricId: "metric_profit", rightMetricId: "metric_sales", calculationOperator: "RATIO", scale: 100, format: "percent", synonyms: ["利润率"], status: "DRAFT" },
  ],
  relations: [
    { id: "rel_sales_customer", name: "销售归属客户", sourceObjectId: "obj_sales", targetObjectId: "obj_customer", type: "REFERENCE", cardinality: "MANY_TO_ONE", sourcePropertyId: "prop_customer_id", targetPropertyId: "prop_customer_pk", joinExpression: "销售事件.customer_id = 客户.customer_id", direction: "SOURCE_TO_TARGET", required: true, enabled: true, fanoutRisk: "NONE", status: "DRAFT" },
    { id: "rel_sales_region", name: "销售归属区域", sourceObjectId: "obj_sales", targetObjectId: "obj_region", type: "REFERENCE", cardinality: "MANY_TO_ONE", sourcePropertyId: "prop_region_id", targetPropertyId: "prop_region_pk", joinExpression: "销售事件.region_id = 区域.region_id", direction: "SOURCE_TO_TARGET", required: false, enabled: true, fanoutRisk: "NONE", status: "DRAFT" },
  ],
  dimensionHierarchies: [],
};
